sudo: false
language: java
jdk:
   - oraclejdk8

services:
 - mongodb
 - rabbitmq

addons:
 apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

before_install:
 - chmod +x gradlew